insert into category (description) values ('American'); 
insert into category (description) values ('Italian');
insert into category (description) values ('Mexican');
insert into category (description) values ('Fast Food');
insert into unit_of_measure (`unit_of_measure`) values ('Teaspoon');
insert into unit_of_measure (`unit_of_measure`) values ('Tablespoon');
insert into unit_of_measure (`unit_of_measure`) values ('Cup');
insert into unit_of_measure (`unit_of_measure`) values ('Pinch');
insert into unit_of_measure (`unit_of_measure`) values ('Ounce');
insert into unit_of_measure (`unit_of_measure`) values ('dash');
INSERT INTO unit_of_measure (`unit_of_measure`) VALUES ('Pint');
INSERT INTO unit_of_measure (`unit_of_measure`) VALUES ('Each');